### ISSUE TITLE
Explicitly annotate types / Sema-infered types without DerefType crash function modeling

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#48]
"I have partly fixed this by not implicitly infering Pointer/Owner in classifyTypeCategory when we cannot deduce the DerefType.
We can still get a null DerefType on explicitly annotated classes or classes that have been infered by Sema (i.e. std types).
I wanted to change that to return a DerefType "void" instead, but classifyTypeCategory currently does not have access to an ASTContext,
so it cannot create a void type out of thin air."

**Comment by Xazax-hun** [comment]
Having deref types would be very handy for the statement-local analysis too.

For example if I see something like:
```
UnannotatedType local;
return GslPointer(local);
```

Should I warn? If `local` was annotated as `Owner`, sure. But otherwise, if `UnannotatedType` have pointer semantics but is not annotated, this would be a false positive. 

One way to resolve this issue would be to check the `DerefType` and only warn if `DerefType` == `UnannotatedType`.

**Comment by mgehre** [comment]
I agree that having a DerefType allows to infer function annotations (also on constructors). If we have no DerefType, we cannot infer function annotations, so we rely on user-written ones, implicitly-generated ones or we disable the analysis (possibly a false-negative).

**Comment by mgehre** [comment]
The paper has been updated to say that types without DerefType will have an unspecified DerefType.

**Comment by mgehre** [comment]
Fixed in 0a6804ff982260f206e1d27dd3f1d5d4b34d4ba6
