### ISSUE TITLE
Assert failure (2)

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#58]
```
void b() {
  struct {
    char a;
  } c[]{};
  c[0].a;
}
```

**Comment by Xazax-hun** [comment]
After a quick look the problem might be the following:
We do not track pset for the elements of the array individually, but we have only one pset for the whole array (which has the type array). But we assume, when we reference a field of a pset, the type of the pset needs to be a record. But in this case this is an array. Since we do not want to track each individual elements of the array, I think the best solution would be to add a special case and as long as we have an array, let's get the element type. It should also work for multidimensional arrays.
I wonder if there are other constructs with similar problems, like unions.

**Comment by mgehre** [comment]
Fixed in d059eff02f694c7988607a8cd0bf286f855d99f3
